<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="soft" nsURI="/Users/ysakanaka/HomeWork/SEClass/GameMapEditor/src"
    nsPrefix="sf">
  <eSubpackages name="mapping" nsURI="/Users/ysakanaka/HomeWork/SEClass/GameMapEditor/src/mapping"
      nsPrefix="mp">
    <eClassifiers xsi:type="ecore:EClass" name="Map">
      <eOperations name="init">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="&#x9;cells = new Cell[3][width][height];&#xA;&#xA;&#x9;&#x9;for (int z = 0; z &lt; 3; z++) {&#xA;&#x9;&#x9;&#x9;for (int x = 0; x &lt; width; x++) {&#xA;&#x9;&#x9;&#x9;&#x9;for (int y = 0; y &lt; height; y++) {&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;CellImpl myCell = new CellImpl();&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;myCell.init(x, y);&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;cells[z][x][y] = myCell;&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#xA;&#x9;&#x9;myLogs = new LogsImpl();"/>
        </eAnnotations>
        <eParameters name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getCellFromCurrentLayer" eType="#//mapping/Cell">
        <eParameters name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getCellFromSpecifiedLayer" eType="#//mapping/Cell">
        <eParameters name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="layer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="myLogs" lowerBound="1"
          eType="#//mapping/Logs" changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentLayer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cells" lowerBound="1"
          eType="#//mapping/CellArray"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLayer" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="3"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetsSet" lowerBound="1"
          eType="#//mapping/AssetArray"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapheight" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="20"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapwidth" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="20"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="AssetArray" instanceClassName="soft.mapping.Asset[]"/>
    <eClassifiers xsi:type="ecore:EClass" name="Logs">
      <eOperations name="undo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="redo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="removelog"/>
      <eOperations name="addlog">
        <eParameters name="op" eType="#//mapping/Operation"/>
      </eOperations>
      <eOperations name="init"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maps" upperBound="-1"
          eType="#//mapping/Map" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="current" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="logdata" upperBound="-1"
          eType="#//mapping/Operation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cell" eSuperTypes="#//main/Serializable">
      <eOperations name="init" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="Position myPos = new PositionImpl();&#xA;&#xA;myPos.setX(x);&#xA;myPos.setY(y);&#xA;myPos.setMyCell(this);&#xA;&#xA;this.setPosition(myPos);&#xA;&#xA;myAsset = null;&#xA;myAssetArea = null;&#xA;referenceCell = null;"/>
        </eAnnotations>
        <eParameters name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="toString" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="Position myPos = getPosition();&#xA;&#x9;&#x9;return &quot;Cell (&quot;+myPos.getX()+&quot;,&quot;+myPos.getY()+&quot;)&quot;;"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="1"
          eType="#//mapping/Position" eOpposite="#//mapping/Position/myCell"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="myAsset" eType="#//mapping/Asset"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="myAssetArea" eType="#//mapping/AreaVector"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceCell" eType="#//mapping/Cell"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellColor" lowerBound="1"
          eType="#//mapping/Color" defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Position" eSuperTypes="#//main/Serializable">
      <eOperations name="init"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="myCell" lowerBound="1"
          eType="#//mapping/Cell" unsettable="true" containment="true" eOpposite="#//mapping/Cell/position"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation">
      <eOperations name="init"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="layer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="area" eType="#//mapping/AreaVector"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="beforeMap" eType="#//mapping/Map"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="afterMap" eType="#//mapping/Map"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AreaVector">
      <eOperations name="init"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//mapping/Position"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//mapping/Position"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Asset" abstract="true">
      <eOperations name="init"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="myGraphics2d" eType="#//mapping/Graphics2D"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Graphics2D" instanceClassName="java.awt.Graphics2D"/>
    <eClassifiers xsi:type="ecore:EDataType" name="CellArray" instanceClassName="soft.mapping.Cell[][][]"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Color" instanceClassName="java.awt.Color"/>
  </eSubpackages>
  <eSubpackages name="main" nsURI="/Users/ysakanaka/HomeWork/SEClass/GameMapEditor/src/main"
      nsPrefix="main">
    <eClassifiers xsi:type="ecore:EClass" name="MyGameMapEditor">
      <eOperations name="main"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Editor"/>
    <eClassifiers xsi:type="ecore:EClass" name="Window">
      <eOperations name="init"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="File">
      <eOperations name="makeNewFile"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Serializable" instanceClassName="java.io.Serializable"
        abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="fileio" nsURI="/Users/ayumi/SE" nsPrefix="fileio">
    <eClassifiers xsi:type="ecore:EClass" name="XmlWriter">
      <eOperations name="init"/>
      <eOperations name="map2xml">
        <eParameters name="filepath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XmlReader">
      <eOperations name="init"/>
      <eOperations name="xml2map" eType="#//mapping/Map">
        <eParameters name="filepath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="xml2assets" eType="#//mapping/Asset">
        <eParameters name="filepath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MyImageReader">
      <eOperations name="init"/>
      <eOperations name="image2graphics2D" eType="#//mapping/Graphics2D">
        <eParameters name="filename" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="image2asset" eType="#//mapping/Asset">
        <eParameters name="filename" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MyImageWriter">
      <eOperations name="init"/>
      <eOperations name="graphics2D2image">
        <eParameters name="g" lowerBound="1" eType="#//mapping/Graphics2D"/>
      </eOperations>
      <eOperations name="asset2graphics2D">
        <eParameters name="asset" lowerBound="1" eType="#//mapping/Asset"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="graphics" nsURI="/Users/tkn/class/software-engineering" nsPrefix="graphics">
    <eClassifiers xsi:type="ecore:EClass" name="ImageProcess">
      <eOperations name="blending" eType="#//mapping/Graphics2D">
        <eParameters name="wholeMap" eType="#//graphics/MapImage"/>
        <eParameters name="renewArea" eType="#//mapping/AreaVector"/>
        <eParameters name="currentLayer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="scaling" eType="#//mapping/Graphics2D">
        <eParameters name="wholeMap" eType="#//mapping/Graphics2D"/>
        <eParameters name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opacity" eType="#//graphics/FloatArray"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="MapImage" instanceClassName="java.awt.Graphics2D[]"/>
    <eClassifiers xsi:type="ecore:EDataType" name="FloatArray" instanceTypeName="EFloat[]"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssetProcess">
      <eOperations name="backgroundFilter" eType="#//mapping/Graphics2D">
        <eParameters name="origin" eType="#//mapping/Graphics2D"/>
        <eParameters name="color" eType="#//mapping/Color"/>
      </eOperations>
      <eOperations name="normalizeAsset" eType="#//mapping/Graphics2D">
        <eParameters name="asset" eType="#//mapping/Asset"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="thumbnailX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="thumbnailY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
